//
//  UsuarioWorker.swift
//  TrailerGTV
//
//  Created by Humberto  Julião on 19/05/16.
//  Copyright (c) 2016 Daniel Trevisan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

class UsuarioWorker {
  // MARK: Business Logic
  
}
